### ISSUE TITLE
Getting package version from `package.json`

### ISSUE THREAD

**Issue by filips123** [pikapkg/standard-pkg#7]
How to get package version from `package.json`? I want to get it as a variable in the main script to later use it.

I tried this (`src/index.js`):

```js
import { version } from '../package.json'
```

However, when building with Pika Pack, I get this error:

```
$ pika build
@pika/pack v0.5.0
[1/6] Validating source...
[2/6] Preparing pipeline...
      ❇️  pkg/
[3/6] Running @pika/plugin-standard-pkg...
Unexpected file extension: ../package.json
      📝  pkg/dist-src/index.js [esnext]
      » Linting with standard-pkg...

dist-src/index.js
  ⚠️  [4:0] "../package.json": Valid relative imports must include the ".js" file extension.
  ⚠️  [4:0] "../package.json": Valid imports can only import from the dist directory or the sibling `assets/` directory.

✘ 2 issues found.
[4/6] Running @pika/plugin-build-node...
Error: Could not resolve '../package.json' from pkg/dist-src/index.js
    at error (/usr/src/app/node_modules/rollup/dist/rollup.js:9558:30)
    at ModuleLoader.handleMissingImports (/usr/src/app/node_modules/rollup/dist/rollup.js:16628:17)
    at ModuleLoader.<anonymous> (/usr/src/app/node_modules/rollup/dist/rollup.js:16679:26)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/rollup/dist/rollup.js:40:28)
Error: Command failed with exit code 1 (EPERM): npx pika-pack
    at makeError (/usr/local/share/.config/yarn/global/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/usr/local/share/.config/yarn/global/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

I have the following pipeline:

```json
{
  "@pika/pack": {
    "pipeline": [
      [
        "@pika/plugin-standard-pkg"
      ],
      [
        "@pika/plugin-build-node"
      ],
      [
        "@pika/plugin-build-web"
      ]
    ]
  }
}

**Comment by filips123** [comment]
@FredKSchott Is now any way to get package version from `package.json`?

**Comment by FredKSchott** [comment]
You'll want to use fs.readFile + JSON.stringify. 

`import { version } from '../package.json'` will probably be supported soon, but for now I believe it breaks in Node.js's native ESM support.

Sorry I missed this question originally!
